### PR TITLE
Explicitly request Electron microphone permission

### PR DESCRIPTION
**Pull request by claar**
This change fixes the microphone on macOS when bundled as an Electron app. At least works for me!

### CODE REVIEW

**Review by elfvingralf — APPROVED** [review]
This is great, thank you for this!

**Comment by elfvingralf** [comment]
@claar works in my end as well, thank you for this! ❤️  This microphone issue was really annoying because without it fixed you're required to run it from a terminal. Now the app feels complete!

I think I spent as much time trying to get the microphone to work after packaging as I did building the rest of the app!

**Comment by claar** [comment]
@elfvingralf Happy to help! Appropriately for this app, I have to give credit to ChatGPT for the fix. I literally pasted in index.js and asked ChatGPT how to modify the app to request microphone permission on OS X. 🤣

**Comment by elfvingralf** [comment]
@claar I tried to do the same, but it sent me down various fruitless rabbit holes! 

This is great. I think I'll build on this approach and request the other security/privacy access bits upfront as well!

**Pull request merged**
